version: "3.3"
services:
  broadcast:
    image: broadcast-demo
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: unless-stopped
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 5432:5432
    restart: unless-stopped
